Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [5]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
type(list_)
list_

['1', '2', '3', '4', '5']

In [6]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list.dtype


dtype('<U1')

In [6]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [12]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
print(list_)
for i in list_:
    print(i, type(i))



['1', '2', '3', '4', '5']
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [11]:
import numpy as np
array_list = np.array(object = list_)
print(array_list)
for i in array_list:
    print(i, type(i))


['1' '2' '3' '4' '5']
1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


#Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.


In [13]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [27]:
array_list.dtype

dtype('int64')

In [25]:
type(list_)

list

#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size


In [30]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
np.shape(num_array)

(2, 3)

In [31]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
np.size(num_array)

6

#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]


In [37]:
import numpy as np
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [46]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])